config/routes.rb
AirboRailsTestProject::Application.routes.draw do
  resources :charges

end

app/models/charge.rb
class Charge < ActiveRecord::Base
   belongs_to :customer
   
   scope :failed_charges, -> { where(paid: false, refunded: false) }
   scope :disputed_charges, -> { where(paid: false, refunded: true) }
   scope :successful_charges, -> { where(paid: true, refunded: false) }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :charges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]

  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
    @failed_charges = Charge.failed_charges
    @disputed_charges = Charge.disputed_charges
    @successful_charges = Charge.successful_charges
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charge }
      else
        format.html { render action: 'new' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:created, :paid, :amount, :currency, :refunded, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :created %><br>
    <%= f.number_field :created %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br>
    <%= f.check_box :refunded %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1>List1</h1>
<table>
  <thead>
    <tr>
      <th>Created</th>
      <th>Paid</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Refunded</th>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>  	
    <% @failed_charges.each do |charge| %>
      <tr class="list1-background">      
        <td><%= charge.created %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer_id %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>List 2</h1>

<table>
  <thead>
    <tr class="list2-background">
      <th>Created</th>
      <th>Paid</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Refunded</th>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @disputed_charges.each do |charge| %>
      <tr class="list2-background">
        <td><%= charge.created %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer_id %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>List3</h1>

<table>
  <thead>
    <tr class="list3-background">
      <th>Created</th>
      <th>Paid</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Refunded</th>
      <th>Customer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @successful_charges.each do |charge| %>
      <tr class="list3-background">
        <td><%= charge.created %></td>
        <td><%= charge.paid %></td>
        <td><%= charge.amount %></td>
        <td><%= charge.currency %></td>
        <td><%= charge.refunded %></td>
        <td><%= charge.customer_id %></td>
        <td><%= link_to 'Show', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Destroy', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created:</strong>
  <%= @charge.created %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @charge.paid %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @charge.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @charge.currency %>
</p>

<p>
  <strong>Refunded:</strong>
  <%= @charge.refunded %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @charge.customer_id %>
</p>

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirboRailsTestProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>